init:
  - git config --global core.autocrlf true
environment:
  matrix:
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
install:
  - "npm install"
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
