init:
  - git config --global core.autocrlf false
environment:
  matrix:
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "iojs"
    - nodejs_version: "0.12"
install:
  - "npm install"
test_script:
  - "npm test"
