'use strict';
module.exports.usage   = require('./modules/usage');
module.exports.put     = require('./modules/put');
module.exports.take    = require('./modules/take');
module.exports.list    = require('./modules/list');
module.exports.open    = require('./modules/open');
module.exports.install = require('./modules/install');
module.exports.close   = require('./modules/close');
module.exports.scripts = require('./modules/scripts');
module.exports.run     = require('./modules/run');
